package cz.endless.conflict.enums;

/**
 * Created by snajfi1 on 03.03.2018.
 */
public enum BonusType {
    SWORDSMAN_TRAINING,
    ARCHERS_TRAINING,
    LANCER_TRAINING,
    HORSEMAN_TRAINING,
    ARMY_STRENGTH,
    ATTACK_STRENGTH,
    DEFENSE_STRENGTH,
    GOLD_PRODUCTION,
    FOOD_PRODUCTION,
    WOOD_PRODUCTION,
    RESEARCH_POINT_PRODUCTION,
    POINTS_OF_CONSTRUCTION_PRODUCTION,
    BARRACK_PRODUCTION,
    STABLE_PRODUCTION,
    RESOURCE_PRODUCTION,
    UNIT_PRODUCTION,
    TACTIC_STRENGTH,
    TACTIC_ATTACK,
    TACTIC_DEFENSE,
    NIGHT_AMBUSH_ATTACK,
    SHOOTING_ATTACK,
    TRAPPING_ATTACK,
    HUNTING_ATTACK,
    NIGHT_AMBUSH_DEFENSE,
    SHOOTING_DEFENSE,
    TRAPPING_DEFENSE,
    HUNTING_DEFENSE,
    UNIT_LOSES,
    HAPPINESS

}
